-- CreateTable
CREATE TABLE `nets` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `time` DATETIME(0) NULL,
    `BSSID` BIGINT NULL,
    `ESSID` VARCHAR(32) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

